import type { Metadata } from "next";
import "./globals.css";
import Navi from "./components/Navi";

export const metadata: Metadata = {
  title: "TMDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Navi />
        {children}
      </body>
    </html>
  );
}
